"""Seed topology: a realistic e-commerce microservice estate spread across Vultr + Nebius."""

SERVICES = [
    # name, tier, cloud, region, runtime, owner, base latency ms, base rps, image
    dict(name="edge-cdn", tier="edge", cloud="vultr", region="ewr", runtime="nginx", owner="platform", lat=12, rps=4200, image="nginx:1.27"),
    dict(name="api-gateway", tier="edge", cloud="vultr", region="ewr", runtime="envoy", owner="platform", lat=28, rps=3900, image="envoyproxy/envoy:v1.31"),
    dict(name="auth-service", tier="core", cloud="vultr", region="ewr", runtime="go", owner="identity", lat=34, rps=2100, image="acme/auth:2.14.1"),
    dict(name="user-service", tier="core", cloud="vultr", region="ewr", runtime="node", owner="identity", lat=41, rps=1500, image="acme/users:5.3.0"),
    dict(name="catalog-service", tier="core", cloud="nebius", region="eu-north1", runtime="java", owner="commerce", lat=55, rps=2600, image="acme/catalog:9.1.2"),
    dict(name="search-service", tier="core", cloud="nebius", region="eu-north1", runtime="python", owner="commerce", lat=72, rps=1800, image="acme/search:3.8.0"),
    dict(name="cart-service", tier="core", cloud="vultr", region="ewr", runtime="node", owner="commerce", lat=38, rps=1300, image="acme/cart:4.0.7"),
    dict(name="checkout-service", tier="core", cloud="vultr", region="ewr", runtime="go", owner="payments", lat=64, rps=900, image="acme/checkout:7.2.0"),
    dict(name="payment-service", tier="core", cloud="vultr", region="ewr", runtime="java", owner="payments", lat=88, rps=850, image="acme/payments:6.5.3"),
    dict(name="order-service", tier="core", cloud="nebius", region="eu-north1", runtime="go", owner="fulfilment", lat=47, rps=880, image="acme/orders:8.0.1"),
    dict(name="inventory-service", tier="core", cloud="nebius", region="eu-north1", runtime="python", owner="fulfilment", lat=51, rps=1100, image="acme/inventory:2.9.4"),
    dict(name="notification-service", tier="async", cloud="nebius", region="eu-north1", runtime="node", owner="growth", lat=30, rps=600, image="acme/notify:1.12.0"),
    dict(name="fraud-ml", tier="ml", cloud="nebius", region="eu-north1", runtime="python-gpu", owner="risk", lat=120, rps=400, image="acme/fraud-ml:0.9.3"),
    dict(name="kafka", tier="data", cloud="nebius", region="eu-north1", runtime="kafka", owner="platform", lat=6, rps=9000, image="bitnami/kafka:3.7"),
    dict(name="redis-cache", tier="data", cloud="vultr", region="ewr", runtime="redis", owner="platform", lat=2, rps=12000, image="redis:7.2"),
    dict(name="postgres-primary", tier="data", cloud="vultr", region="ewr", runtime="postgres", owner="platform", lat=9, rps=5200, image="postgres:16.3"),
    dict(name="opensearch", tier="data", cloud="nebius", region="eu-north1", runtime="opensearch", owner="platform", lat=18, rps=2400, image="opensearchproject/opensearch:2.15"),
    dict(name="object-store", tier="data", cloud="vultr", region="ewr", runtime="s3", owner="platform", lat=22, rps=1400, image="minio/minio:RELEASE.2024-08"),
]

# (from, to) — "from DEPENDS_ON to"
EDGES = [
    ("edge-cdn", "api-gateway"),
    ("api-gateway", "auth-service"),
    ("api-gateway", "user-service"),
    ("api-gateway", "catalog-service"),
    ("api-gateway", "search-service"),
    ("api-gateway", "cart-service"),
    ("api-gateway", "checkout-service"),
    ("api-gateway", "order-service"),
    ("auth-service", "postgres-primary"),
    ("auth-service", "redis-cache"),
    ("user-service", "postgres-primary"),
    ("user-service", "auth-service"),
    ("catalog-service", "postgres-primary"),
    ("catalog-service", "redis-cache"),
    ("catalog-service", "object-store"),
    ("search-service", "opensearch"),
    ("search-service", "catalog-service"),
    ("cart-service", "redis-cache"),
    ("cart-service", "catalog-service"),
    ("checkout-service", "cart-service"),
    ("checkout-service", "payment-service"),
    ("checkout-service", "inventory-service"),
    ("checkout-service", "order-service"),
    ("payment-service", "fraud-ml"),
    ("payment-service", "postgres-primary"),
    ("payment-service", "kafka"),
    ("order-service", "postgres-primary"),
    ("order-service", "kafka"),
    ("order-service", "inventory-service"),
    ("inventory-service", "postgres-primary"),
    ("inventory-service", "kafka"),
    ("notification-service", "kafka"),
    ("notification-service", "user-service"),
    ("fraud-ml", "object-store"),
    ("fraud-ml", "redis-cache"),
]

# Simulated cloud inventory used by the cost / governance auditor (replaced by live data when keys exist)
INVENTORY = [
    dict(id="vultr-8f3a", cloud="vultr", region="ewr", type="vc2-8c-32gb", label="api-gateway-2", service="api-gateway", monthly=160, cpu_avg=41, tags={"env": "prod", "owner": "platform"}, public_ip=True),
    dict(id="vultr-1c22", cloud="vultr", region="ewr", type="vc2-4c-16gb", label="auth-1", service="auth-service", monthly=80, cpu_avg=37, tags={"env": "prod", "owner": "identity"}, public_ip=False),
    dict(id="vultr-77b0", cloud="vultr", region="ewr", type="vc2-16c-64gb", label="pg-primary", service="postgres-primary", monthly=320, cpu_avg=58, tags={"env": "prod"}, public_ip=False),
    dict(id="vultr-c0de", cloud="vultr", region="ewr", type="vc2-8c-32gb", label="staging-worker-old", service=None, monthly=160, cpu_avg=1, tags={}, public_ip=True),
    dict(id="vultr-9a91", cloud="vultr", region="ewr", type="vc2-2c-4gb", label="jumpbox", service=None, monthly=20, cpu_avg=0, tags={"env": "prod"}, public_ip=True),
    dict(id="nebius-h100-01", cloud="nebius", region="eu-north1", type="gpu-h100-1x", label="fraud-ml-train", service="fraud-ml", monthly=2100, cpu_avg=3, tags={"env": "prod", "owner": "risk"}, public_ip=False),
    dict(id="nebius-h100-02", cloud="nebius", region="eu-north1", type="gpu-h100-1x", label="fraud-ml-serve", service="fraud-ml", monthly=2100, cpu_avg=62, tags={"env": "prod", "owner": "risk"}, public_ip=False),
    dict(id="nebius-cpu-14", cloud="nebius", region="eu-north1", type="cpu-16vcpu-64gb", label="catalog-1", service="catalog-service", monthly=290, cpu_avg=44, tags={"env": "prod", "owner": "commerce"}, public_ip=False),
    dict(id="nebius-cpu-15", cloud="nebius", region="eu-north1", type="cpu-16vcpu-64gb", label="catalog-2", service="catalog-service", monthly=290, cpu_avg=12, tags={"env": "prod", "owner": "commerce"}, public_ip=False),
    dict(id="nebius-cpu-22", cloud="nebius", region="eu-north1", type="cpu-8vcpu-32gb", label="kafka-broker-3", service="kafka", monthly=150, cpu_avg=49, tags={"env": "prod"}, public_ip=False),
    dict(id="nebius-vol-7", cloud="nebius", region="eu-north1", type="ssd-2tb", label="orphan-volume-2tb", service=None, monthly=180, cpu_avg=None, tags={}, public_ip=False),
]
